an:
  frontpage: 100
  main: 100
ar:
  frontpage: 100
  main: 53
be_BY:
  frontpage: 100
  main: 100
bg_BG:
  frontpage: 18
  main: 44
ca:
  frontpage: 81
  main: 83
cmn:
  frontpage: 0
  main: 31
cs:
  frontpage: 100
  main: 84
da:
  frontpage: 100
  main: 99
de:
  frontpage: 100
  main: 100
el:
  frontpage: 100
  main: 100
eo:
  frontpage: 100
  main: 97
es:
  frontpage: 100
  main: 99
fa_IR:
  frontpage: 100
  main: 13
fi:
  frontpage: 0
  main: 7
fr:
  frontpage: 100
  main: 99
ga_IE:
  frontpage: 37
  main: 48
gl:
  frontpage: 51
  main: 75
he:
  frontpage: 100
  main: 71
hr:
  frontpage: 100
  main: 50
hu:
  frontpage: 100
  main: 100
id:
  frontpage: 51
  main: 57
it:
  frontpage: 100
  main: 98
it_CH:
  frontpage: 0
  main: 0
ja:
  frontpage: 62
  main: 68
km:
  frontpage: 0
  main: 52
ko:
  frontpage: 97
  main: 61
lv:
  frontpage: 0
  main: 0
mi:
  frontpage: 2
  main: 0
mk:
  frontpage: 100
  main: 58
ml:
  frontpage: 0
  main: 56
nl_NL:
  frontpage: 100
  main: 99
pl:
  frontpage: 100
  main: 19
pt_BR:
  frontpage: 100
  main: 100
pt_PT:
  frontpage: 25
  main: 10
ro:
  frontpage: 100
  main: 99
ru:
  frontpage: 100
  main: 61
sk:
  frontpage: 100
  main: 100
sl:
  frontpage: 100
  main: 90
sr:
  frontpage: 100
  main: 100
sr_RS:
  frontpage: 100
  main: 100
sv:
  frontpage: 100
  main: 99
te:
  frontpage: 18
  main: 28
tr:
  frontpage: 100
  main: 100
uk:
  frontpage: 100
  main: 84
ur:
  frontpage: 0
  main: 0
ur_PK:
  frontpage: 0
  main: 0
vi:
  frontpage: 0
  main: 46
zh_TW:
  frontpage: 100
  main: 100
